name: Release SocialApis

on:
  push:
    branches:
    - release/nupkg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - run: dotnet build --configuration Release
    - run: dotnet nuget push SocialApis/bin/Release/SocialApis.*.nupkg -k ${{ secrets.NUGET_PUSH_KEY }} -s ${{ secrets.NUGET_REPOSITORY_URL }}
