name: Test package

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      steps:
        - uses: actions/checkout@v2
        - name: Setup dotnet
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.0.x'
        - name: Install dependencies
          run: dotnet restore
        - name: Run test
          run: dotnet test --logger trx --results-directory "TestResult"
        - name: Upload dotnet test results
          uses: actions/upload-artifact@v2
          with:
            name: dotnet-result
            path: TestResult
          # Use always() to always run this step to publish test results when there are test failures
          if: ${{ always() }}